### ISSUE TITLE
Documentation not Updated

### ISSUE THREAD

**Issue by abhiramani-iptiq** [Azure/helm-elasticstack#10]
Hi,
Even though subject says AKS.the documentation is not really updated for Kubernetes service
i need to implement in Azure Kubernetes Service(AKS)

can you clarify

**Comment by brndkfr** [comment]
repo is going into read-only and [archive](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/archiving-repositories) mode
